# Generated by Django 4.1.2 on 2022-11-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='product_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
