# Generated by Django 4.1.2 on 2022-11-14 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='selected_brand',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='selected_product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='selected_store',
            new_name='store',
        ),
    ]
